# lexik_jwt_authentication:
#     secret_key: '%env(resolve:JWT_SECRET_KEY)%'
#     public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
#     pass_phrase: '%env(JWT_PASSPHRASE)%'
lexik_jwt_authentication:
  secret_key: '%kernel.project_dir%/config/jwt/private.pem' # Path to your private key
  public_key: '%kernel.project_dir%/config/jwt/public.pem' # Path to your public key
  pass_phrase: '1234' # Same passphrase used during key generation
  token_ttl: 3600 # Token validity duration in seconds (optional)

